### ISSUE TITLE
Google No

### ISSUE THREAD

**Issue by josephdjenandji** [ryan-d-williams/MMM-GoogleSheets#10]

**Comment by josephdjenandji** [comment]
<img width="959" alt="Screen Shot 2020-09-18 at 1 18 16 PM" src="https://user-images.githubusercontent.com/16668643/93592007-b20dd500-f9b1-11ea-8315-15375538b62f.png">

**Comment by ryan-d-williams** [comment]
@josephdjenandji what step in the process is this?

**Comment by josephdjenandji** [comment]
Click Deploy
If this is your first time deploying the app, it will ask you to grant permissions
Click "Review Permissions"
**Click on your gmail account (the one that owns the spreadsheet)
In the popup that says "This app isn't verified" click on "Advanced" and then "Go to {project name} (unsafe)"**

**Comment by ryan-d-williams** [comment]
@josephdjenandji are you signed into your google account when you press deploy? Do you mind posting a screenshot of what you're seeing prior to pressing deploy?

**Comment by ryan-d-williams** [comment]
@josephdjenandji closing this issue because it is stale. Feel free to reopen if you are still having this issue.
