### ISSUE TITLE
Displaying cached data?

### ISSUE THREAD

**Issue by gonzonia** [ryan-d-williams/MMM-GoogleSheets#11]
I'm noticing a weird behavior but I can't seem to nail down the cause. 
I've got two sheets I'm displaying. Each sheet is a kids homework for the week. 
In the config file, I have them as two different modules displaying in different areas of the screen. 
They were working great until this week when one of them decided to stop updating and continues to display last week's data despite the Google Sheet being updated. 

But wait, it gets weirder. I figured it was just a network hiccup, and reloaded the page and all looked well. Then at some point, it reverts to the old data again! It did this today. I verified the URL in the config file, reloaded, and then an hour or so later noticed it was showing old data again. 

Side notes that may or may not be relevant- Each Google sheet contains a Sheet 1 & Sheet 2. 
Sheet 1 is populated from various ImportHTML statements
Sheet 2 is populated from some transpose statements to pull from Sheet 1.

**Comment by ryan-d-williams** [comment]
@gonzonia I can't seem to replicate your issue. If the data in your sheet(s) is not private / sensitive, do you mind posting the links to the sheets with what you expect to see and what you're actually seeing?

**Comment by gonzonia** [comment]
At some point this resolved. I'm going to close it. If I notice again I'll re-open and try to post more info.
