### ISSUE TITLE
Unable to Deploy as Web App

### ISSUE THREAD

**Issue by citadella** [ryan-d-williams/MMM-GoogleSheets#12]
I'm unable to get past the Deploy as web app step, sitting stuck on this screen indefinitely:

![image](https://user-images.githubusercontent.com/31351568/95871513-07998f80-0d6e-11eb-81ba-bb6173f112a3.png)

Is there something amiss behind the scenes?

**Comment by ryan-d-williams** [comment]
@citadella I'm not entirely sure why it would be loading indefinitely. Might be a service issue with google apps script. Have you tried it on multiple days or just the one time?

**Comment by ryan-d-williams** [comment]
@citadella closing this issue because it is stale. Feel free to reopen if you are still having this issue.
