### ISSUE TITLE
TypeError: Cannot read property '0' of undefined (line 11, file "Code")

### ISSUE THREAD

**Issue by batuhanyklmz** [ryan-d-williams/MMM-GoogleSheets#14]
When I deploy and use link from script, i keep getting this error. On the magic mirror module, it is opening, but it is keep waiting to load. Do you have any idea guys? I have done everything in instructions.

**Comment by ryan-d-williams** [comment]
@batuhanyklmz if the data in your sheet is not sensitive or private, can you please post the link? That will help me determine what his going wrong with your module

**Comment by batuhanyklmz** [comment]
I allow my excel data to everyone from sharing option. Let me share the config with you. https://drive.google.com/file/d/1ilquDMKfh-23HpvWyHsp765O-tGj-U1G/view?usp=sharing 

Here you can find my config.js file.

**Comment by batuhanyklmz** [comment]
by the way I know it is is comment section. I did it to ignore that part.

**Comment by ryan-d-williams** [comment]
@batuhanyklmz the link your config file to your script does not work (https://script.google.com/macros/s/AKfycbxGe9TaH7ADp221HblDkOYwfgcnRRmLqJ-XJHNuTnpDf94AmZqb-jn3/exec). 

This is likely a deployment problem. Did you deploy the script?

**Comment by batuhanyklmz** [comment]
Yes I deployed it maybe 16 times. Version says 16 in the deployment.

**Comment by ryan-d-williams** [comment]
Can you post the link it gives you when you deploy? The link you provided in the config is not correct - try typing that link into the browser and you will see it does not lead to a google apps script

**Comment by batuhanyklmz** [comment]
![1](https://user-images.githubusercontent.com/32879633/108223199-9d915c80-714a-11eb-8da1-9cf665a3dadf.PNG)
![2](https://user-images.githubusercontent.com/32879633/108223200-9e29f300-714a-11eb-9b56-12e25b2a7ea3.PNG)

https://script.google.com/macros/s/AKfycbxGe9TaH7ADp221HbIDkOYwfgcnRRmLqJ-XJHNuTnpDf94AmZqb-jn3/exec

**Comment by batuhanyklmz** [comment]
When i deploy new one still it gives same wep app link

**Comment by ryan-d-williams** [comment]
@batuhanyklmz can you post a sample of your spreadsheet? Is there a sheet called "Sheet1"?

**Comment by batuhanyklmz** [comment]
> @batuhanyklmz can you post a sample of your spreadsheet? Is there a sheet called "Sheet1"?

Actually everything works fluently now. Thank you for providing this MMM feature.

**Comment by ryan-d-williams** [comment]
Happy to help!
