### ISSUE TITLE
TypeError: Cannot read property 'parameters' of undefined

### ISSUE THREAD

**Issue by calvinhus** [ryan-d-williams/MMM-GoogleSheets#15]
Hi,
First of all, great module!
But when I try to deploy it I get that error. My mirror displays the module (I see the header and below it just stays loading...)
Any idea what it might be? I did everything as stated.
Thanks

**Comment by ryan-d-williams** [comment]
@calvinhus can you post your config for the module? That's going to be the best way for us to help you debug

**Comment by calvinhus** [comment]
Hi @ryan-d-williams ,

Thanks for your reply.

My config is like this:
```
{
  module: "MMM-GoogleSheets",
  header: "Google Sheets",
  position: "top_right",
  config: {
    url: "https://script.google.com/macros/s/AKfycbxbPm5jbvvPuFRR-N0umlHYd1EZsvNDpNb4OhzK5_Lp/dev",
    sheet: "Folha1",
    range: "A1:B4",
    updateInterval: 1, // minutes
    requestDelay: 250, // ms
    updateFadeSpeed: 0, // ms
    cellStyle: "mimic",
    border: "1px solid #777",
    stylesFromSheet: ["background-color", "color", "font-weight"],
    customStyles: ["font-size: 18px", "padding: 5px"],
    headerStyles: ["font-weight: bold"],
    styleFunc: (rowNum, colNum, cellProps) => {if(rowNum%2 == 0){return "background-color:#666;"}} // Colors every other row background
  }
}
```
Also, my sheet is just like this:

![image](https://user-images.githubusercontent.com/49272934/113731013-50fce300-96f0-11eb-8f0e-919fae9dfd59.png)

**Comment by ryan-d-williams** [comment]
@calvinhus the link you provided was not deployed correctly (it is not available to all, even anonymous). I would recommend reviewing the deployment steps to make sure you have them all correct.

**Comment by calvinhus** [comment]
@ryan-d-williams you're right. I went through all the steps again and it's working now. Many thanks!

**Comment by ryan-d-williams** [comment]
Happy to help!
