### ISSUE TITLE
"..Loading.."

### ISSUE THREAD

**Issue by richcj10** [ryan-d-williams/MMM-GoogleSheets#17]
Any thoughts on how to debug?

`
	{
	  module: "MMM-GoogleSheets",
	  header: "House Rules",
	  position: "top_center",
	  config: {
	    url: "https://script.google.com/macros/s/AKfycbwsIT7L5aJYwLip1s7Clrorg1r_wNsEOctO1dz5/exec",
	    sheet: "HouseRules",
	    range: "A1:B2",
	  }
	},

`

Any way to debug it?

**Comment by ryan-d-williams** [comment]
Looks like there is not a sheet with the name "HouseRules". You should start by verifying that there is a sheet with that exact name.

**Comment by richcj10** [comment]
![image](https://user-images.githubusercontent.com/2460605/113494166-72b95880-94ab-11eb-990d-176c125e38bf.png)

There should be...

**Comment by ryan-d-williams** [comment]
@richcj10 "HouseRules" is the name of the spreadsheet. The name of the sheet is at the bottom of the screen.

It seems as though the sheet name is "Sheet1". If you change the sheet name to "Sheet1" in your config file it should work as expected.

**Comment by richcj10** [comment]
LOL, thanks for that... I feel so stupid...haha

**Comment by ryan-d-williams** [comment]
Happy to help!
