### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by Bluefish67** [ryan-d-williams/MMM-GoogleSheets#19]
I ask because after an installation the whole thing no longer seems to work.
Sorry for my bad English, DeepL was helpful ;)

**Comment by ryan-d-williams** [comment]
@Bluefish67 yes it is maintained (albeit not very frequently). 

Which part of the installation process is not working for you?

**Comment by Bluefish67** [comment]
Directly when creating the code:
function doGet(e){
  return MMMGoogleSheets.doGet(e);
}
and save reports Google:
Syntax error: SyntaxError: Unexpected identifier line: 1 file: Code.gs

**Comment by ryan-d-williams** [comment]
@Bluefish67 can you send a screenshot of what the page looks like before you save and get that syntax error?

If you're getting a syntax error it is likely a copy-paste issue.

**Comment by Bluefish67** [comment]
![bild2](https://user-images.githubusercontent.com/91919376/135991344-f268c911-b739-4942-9190-a0ad5b41f194.PNG)
![bild1](https://user-images.githubusercontent.com/91919376/135991407-4dac82dc-b41f-4176-b71c-fb7e08f320d0.PNG)
No matter how you write it, it always comes up with the same error message. As I understand it, the script does not cope with "doGet".
I hope the English of DeepL is understandable.

**Comment by winfieldlittle** [comment]
Try function instead of funktion.

**Comment by ryan-d-williams** [comment]
@winfieldlittle thank you for responding. @Bluefish67 he is correct, you misspelled function in both locations, and you capitalized it in one (it should be lower case). Closing this issue, feel free to open it again if you are still having problems.
