### ISSUE TITLE
Can this module apply to GoogleDocs?

### ISSUE THREAD

**Issue by CurlyQ12391** [ryan-d-williams/MMM-GoogleSheets#24]
This is less of an issue and more of a question. How easy would it be to apply this same module construct to instead display a GoogleDoc? I would rather use Docs instead of Sheets to display my grocery list, but am too much of a newbie to figure it out myself.

Is this something that could done? perhaps by using a different Apps Library and code?

**Comment by ryan-d-williams** [comment]
@CurlyQ12391 it absolutely can be done! Google Apps Script has a very extensive library of integrations that can be used for Google Sheets, Docs, Slides, etc. [You can find the documentation here](https://developers.google.com/apps-script/guides/docs).

If you don't want to go through the process of creating an entirely new module, you could import your document into google sheets and use this module.
