### ISSUE TITLE
Enhancement Idea - Scrolling data

### ISSUE THREAD

**Issue by xSkydve1x** [ryan-d-williams/MMM-GoogleSheets#27]
It would be great if there was a way to have MMM-GoogleSheets scroll data using a defined range.
Let's say the screen only displayed up to row 15, but you have data down to row 20.  It'd be great to have it scroll the data after X seconds, moving one row up every Y seconds, and then looping back to row 1-13.

Also - I'd love to be able to donate some $ to you for your work on the current version.  Do you have a donation link?

**Comment by ryan-d-williams** [comment]
@xSkydve1x this is a great idea! I will have to do some more research on exactly how I might make that happen but I will mark this as an enhancement for now.

You absolutely don't have to donate any money (I enjoy building these projects) but if you are insistent [here is my buymeacoffee page](https://www.buymeacoffee.com/ryandwilliams).

**Comment by ryan-d-williams** [comment]
@xSkydve1x this has been added! You can check out the readme for how to incorporate scrolling data. Let me know if you have any feedback!
