### ISSUE TITLE
Latest Magic Mirror update breaks MMM-GoogleSheets

### ISSUE THREAD

**Issue by brandonfake69** [ryan-d-williams/MMM-GoogleSheets#30]
I just updated Magic Mirror to version 2.25.0 and now MM won't start unless I comment out the MMM-GoogleSheets section. It was working before the update. Thanks!

**Comment by ryan-d-williams** [comment]
@brandonfake69 what error are you receiving?

**Comment by brandonfake69** [comment]
1. [22666:1004/211737.149436:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
2. MESA-LOADER: failed to retrieve device information
3. MESA-LOADER: failed to retrieve device information
4. MESA-LOADER: failed to retrieve device information
5. MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
6. failed to load driver: kms_swrast
7. MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
8. failed to load swrast driver

**Comment by ryan-d-williams** [comment]
@brandonfake69 I downloaded the most recent version of MM on a new raspberry pi today and added the MMM-GoogleSheets library without any issues. My guess is that it was not this module that was causing the crash (there is nothing in your error messages that would indicate it came from this module).

I'm going to close this for now. Feel free to reopen if you are still having issues.
