### ISSUE TITLE
script do not start

### ISSUE THREAD

**Issue by 1Cedric1** [ryan-d-williams/MMM-GoogleSheets#33]
dear @ryan-d-williams 
thank you for having the possibility to use your interesting module.

I stucked with an error, maybe you could give me an advise ?

thank you for your interest and you help !

Kind regards,

Cédric

step 1 OK : my spreadsheet on Google drive
![Capture d’écran 2024-07-06 à 13 44 02](https://github.com/ryan-d-williams/MMM-GoogleSheets/assets/61581150/0a2cec02-0016-4922-b44d-d98e6f8efc1d)

step 2 OK : adding the library 
![Capture d’écran 2024-07-06 à 13 44 56](https://github.com/ryan-d-williams/MMM-GoogleSheets/assets/61581150/8e458850-891d-4171-bc9b-4aab62d56603)

step 3 OK : update the code
![Capture d’écran 2024-07-06 à 13 45 30](https://github.com/ryan-d-williams/MMM-GoogleSheets/assets/61581150/30d61d02-3546-41df-b9c1-f249cc18d118)

step 4 OK : deployment
![Capture d’écran 2024-07-06 à 13 46 24](https://github.com/ryan-d-williams/MMM-GoogleSheets/assets/61581150/30868f8d-4210-4a39-b48e-976ec310aea9)

step 5 not OK, by clicking on the URL
![Capture d’écran 2024-07-06 à 13 46 37](https://github.com/ryan-d-williams/MMM-GoogleSheets/assets/61581150/c17ba8db-52be-4730-a97d-05254ffe98c8)

step 6 not OK, by running the code, clicking on button "run".
![Capture d’écran 2024-07-06 à 13 46 56](https://github.com/ryan-d-williams/MMM-GoogleSheets/assets/61581150/ca955d7f-0007-4f44-8091-517006e3ead9)

step 7 : detail on appscript
![Capture d’écran 2024-07-06 à 13 47 26](https://github.com/ryan-d-williams/MMM-GoogleSheets/assets/61581150/040fcee8-3921-4f57-8303-caf436f4d26c)

**Comment by omadab** [comment]
I have this same error! It doesnt seem that MMM-GoogleSheets even runs when i start magic mirror!

**Comment by ryan-d-williams** [comment]
@1Cedric1 clicking on the link directly is not expected to work. The module injects parameters into the url to be able to read data from the sheet. Check out these issues below for similar issues:
https://github.com/ryan-d-williams/MMM-GoogleSheets/issues/2
https://github.com/ryan-d-williams/MMM-GoogleSheets/issues/7
https://github.com/ryan-d-williams/MMM-GoogleSheets/issues/29

If you want to test the URL directly, you need to inject the URL parameters. Something like "?sheet=Sheet1&range=A1:B10" added to the end of the URL should work. Make sure to replace it with the correct sheet name and range.

Feel free to post your actual script url (if your google sheets data is not sensitive) and your config file if you want help debugging.

**Comment by ryan-d-williams** [comment]
@omadab What error are you seeing? Feel free to post your actual script url (if your google sheets data is not sensitive) and your config file if you want help debugging.

**Comment by omadab** [comment]
> @omadab What error are you seeing? Feel free to post your actual script url (if your google sheets data is not sensitive) and your config file if you want help debugging.

@ryan-d-williams 
I will open a seperate ticket

**Comment by smey1** [comment]
I have exactly the same problem. is there a solution? Thanks for your help.

**Comment by omadab** [comment]
https://github.com/ryan-d-williams/MMM-GoogleSheets/issues/34

**Comment by ryan-d-williams** [comment]
@smey1 have you read the links in my previous comment or the link in @omadab's comment? The link on it's own is not expected to work. If you post your config we can try to help out.

**Comment by ryan-d-williams** [comment]
@smey1 if you try the full link (https://script.google.com/macros/s/AKfycbye9hXJwyrngb8u7oIdTE9BM5CFxBJPGCvqgRk6mYuPCantQwXRBQBzq25151w3we0nPg/exec?sheet=Inventar&range=A1:B20) you'll see it can't find the sheet name. Are you sure you're spreadsheet has a sheet name called "Inventar"? Note that this is not the name of the _document_ which is found in the upper left corner. This is the name of the _sheet_ that is on the bottom row of the page.

I edited your comment to redact the config. You included your API keys for other modules which is a bad idea on a public post.

**Comment by ryan-d-williams** [comment]
@smey1 I pushed a new README today with updated instructions with pictures. I recommend you follow those new instructions to ensure everything is set up correctly. If you are still having issues feel free to reopen this issue or open a new one.
