### ISSUE TITLE
MMM-GoogleSheets doesn't run

### ISSUE THREAD

**Issue by omadab** [ryan-d-williams/MMM-GoogleSheets#34]
Hi,
I have installed the module in the module folders and added this config:
{
  module: "MMM-GoogleSheets",
  header: "Google Sheets",
  position: "bottom_right",
  config: {
    url: "https://script.google.com/macros/s/AKfycbxmn9YV5XolyGP5PJF7JpO3--QdF2qSqWruOkJJ-l0VXrpVN8NqEZVRE-9dc8J9F_sw5g/exec",
    sheet: "EOY", // Name of the sheet within the document
    range: "A17:L18" // Range of cells to display
  }
}

I have tested the google deployment by adding to the web url: ?sheet=Sheet1&range=A1:B10
It functions properly.

It seems that when i run MagicMirror2 that the module doesn't even get recognized. I see no logs on the console related to GoogleSheets and it doesn't show on the MagicMirror.

Looking forward to your reply,
Thanks

**Comment by ryan-d-williams** [comment]
@omadab your configuration looks good, and I verified that I can see the data with that sheet and range.

My guess would be some kind of MM config issue rather than a module issue. Can you post the full config file? If the module isn't showing up at all and there are no errors in the config, then it is very unlikely to be a module issue, but I can do my best to help debug in case it is.

**Comment by omadab** [comment]
Thanks for the quick reply @ryan-d-williams 
If you see nothing wrong with the module, then ill reach out to MagicMirror2 and try to debug from their end
Here is the config file:
/* Config Sample
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/configuration/introduction.html
 * and https://docs.magicmirror.builders/modules/configuration.html
 *
 * You can use environment variables using a `config.js.template` file instead of `config.js`
 * which will be converted to `config.js` while starting. For more information
 * see https://docs.magicmirror.builders/configuration/introduction.html#enviromnent-variables
 */
let config = {
address: "localhost", // Address to listen on, can be:
// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
// - another specific IPv4/6 to listen on a specific interface
// - "0.0.0.0", "::" to listen on any interface
// Default, when address config is left out or empty, is "localhost"
port: 8080,
basePath: "/", // The URL path where MagicMirror² is hosted. If you are using a Reverse proxy
// you must set the sub path here. basePath must end with a /
ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
// or add a specific IPv4 of 192.168.1.5 :
// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:[192.168.3.0/28](http://192.168.3.0/28)"],

useHttps: false, // Support HTTPS or not, default "false" will use HTTP
httpsPrivateKey: "", // HTTPS private key path, only require when useHttps is true
httpsCertificate: "", // HTTPS Certificate path, only require when useHttps is true

language: "en",
locale: "en-US",
logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
timeFormat: 24,
units: "metric",

modules: [
{
module: "alert",
},
{
module: "updatenotification",
position: "top_bar"
},
{
module: "clock",
position: "top_left"
},
{
module: "calendar",
header: "US Holidays",
position: "top_left",
config: {
calendars: [
{
fetchInterval: 7 * 24 * 60 * 60 * 1000,
symbol: "calendar-check",
url: "https://ics.calendarlabs.com/76/mm3137/US_Holidays.ics"
}
]
}
},
{
module: "compliments",
position: "lower_third"
},
{
module: "weather",
position: "top_right",
config: {
weatherProvider: "openmeteo",
type: "current",
lat: 40.776676,
lon: -73.971321
}
},
{
module: "weather",
position: "top_right",
header: "Weather Forecast",
config: {
weatherProvider: "openmeteo",
type: "forecast",
lat: 40.776676,
lon: -73.971321
}
},
{
module: "newsfeed",
position: "bottom_bar",
config: {
feeds: [
{
title: "New York Times",
url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
}
],
showSourceTitle: true,
showPublishDate: true,
broadcastNewsFeeds: true,
broadcastNewsUpdates: true
}
},
{
    module: 'MMM-GoogleCalendar',
    header: "My Google Private Cal",
    position: "top_left",
    config: {
calendars: [
    {
      symbol: "calendar-week",
      calendarID: "[MYEMAILADDRESS]"
},

{
  module: "MMM-GoogleSheets",
  header: "Google Sheets",
  position: "bottom_right",
  config: {
    url: "https://script.google.com/macros/s/AKfycbxmn9YV5XolyGP5PJF7JpO3--QdF2qSqWruOkJJ-l0VXrpVN8NqEZVRE-9dc8J9F_sw5g/exec",
    sheet: "EOY", // Name of the sheet within the document
    range: "A17:L18" // Range of cells to display
  }
},


            // To add more calendars, replicate the above entry within this array with the respective ID
        ],
    }
},
]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") { module.exports = config; }

**Comment by ryan-d-williams** [comment]
@omadab your config file is incorrect. See this screenshot:
![image](https://github.com/user-attachments/assets/376fac85-b1f5-486b-9647-713cac0d1802)

Notice how the module name is "MMM-GoogleCalendar" but you have config information for MMM-GoogleSheets inside the google calendar module config. If you clean up this issue (MMM-GoogleSheets should be it's own module with it's own config) then it should work as expected.

**Comment by omadab** [comment]
Yes you are right. Thank you, really weird because i ran  npm run config:check but it could not recognize the error. I will work on fixing this thanks
