### ISSUE TITLE
ypeError: Cannot read property '0' of undefined (row: 11, file: "Code")

### ISSUE THREAD

**Issue by emrahaslan** [ryan-d-williams/MMM-GoogleSheets#4]
I applied all your guide on Scprit Editor.
But when I run the module, It shows "loading"

`{
  module: "MMM-GoogleSheets",
  header: "Google Sheets",
  position: "top_right",
  config: {
    url: "https://script.google.com/macros/s/AKfycbw8yIKosRs-BZooJ7cFKG4ppCvImCjmgikIZI0ke0EsIs4I6zs/exec",
    sheet: "Sheet1",
    range: "A1:B1"
  }
}

![1](https://user-images.githubusercontent.com/54321532/88845995-a55cd400-d1ed-11ea-82d4-b6a500ba3773.PNG)
![2](https://user-images.githubusercontent.com/54321532/88845997-a68e0100-d1ed-11ea-9bde-7b67a86bb6a8.PNG)
`

What is the problem ? Could you please help me

**Comment by emrahaslan** [comment]
My Version is :

"name": "magicmirror",
"version": "2.12.0",

**Comment by ryan-d-williams** [comment]
@emrahaslan when I run magic mirror with that exact config it works fine. Are you seeing any errors besides it saying "loading" all the time? Are your other modules running okay?

**Comment by amanzimdwini** [comment]
All running fine

**Comment by ryan-d-williams** [comment]
I noticed it was @amanzimdwini who commented not @emrahaslan. @emrahaslan let me know if you are still seeing issues.

**Comment by emrahaslan** [comment]
Yes my other modules are working fine.
It is always says loading.
I tried to solve ans debug this 4 hours but no result
I want to understand where problem is ç, google script or magic mirror
Please help me

**Comment by emrahaslan** [comment]
Now It's works with white background ! I have to work on stylesheets. thank you
