### ISSUE TITLE
Transparent Background and dynamic size

### ISSUE THREAD

**Issue by emrahaslan** [ryan-d-williams/MMM-GoogleSheets#5]
Hello Ryan,

1- Is it possible to make transparent background for row ? It looks white and black,  I disable it for mirror. 

2- Also I dont need to set exact range, i am expecting to dynamic change, when user add new row , is it possible to show without set new range in config file ?

**Comment by emrahaslan** [comment]
I found solution for my first question with custom css. !
here is my code :

`.module.MMM-GoogleSheets table td {
  line-height: 1.75 !important;
  color:white !important;
  background-color:transparent !important;
 
}`

**Comment by ryan-d-williams** [comment]
@emrahaslan 

1. You can make the background color transparent with the `customStyles` property

Ex: `customStyles: ["background-color: transparent"]`

**Note that setting `cellStyle` to `flat` will also make it appear transparent on your MM. 
Also note that setting your google sheet to a black background for the cells you are displaying will also make it appear transparent on your MM.**

2. There is not a way to have a dynamic range. There is unfortunately not a way for me to programatically know when the user adds a new row. You will need to update the config file.
