### ISSUE TITLE
Mirror don't access sheet

### ISSUE THREAD

**Issue by FallandeGubbe** [ryan-d-williams/MMM-GoogleSheets#55]
Hi, I have followed the instructions, but get error when applying:

 "There was an error in the request: Request failed. Check the URL and logs for more information."

config:

  {
  module: "MMM-GoogleSheets",
  header: "Google Sheets",
  position: "top_right",
  config: {
    url: "https://script.google.com/macros/s/AKfycby6hghPqxI6DTgm3tNmsm2eaRWLVWTF5meCjmde4e3FbRxV79nxEGDebUqRBYrwNDPgUQ/exec",
    sheet: "Blad1",
    range: "D6:D10"
  }
},

**Comment by ryan-d-williams** [comment]
@FallandeGubbe 

When I try that exact config on my MM, it works as expected:
![image](https://github.com/user-attachments/assets/39e83450-c6ea-4f34-a295-4486166e0d2f)

A couple things you can try:
1. Make sure you are restarting the MM after you change the config.
2. Make sure this isn't a firewall issue on your pi. You should be able to view the following url in your browser on the raspberry pi ([https://script.google.com/macros/s/AKfycby6hghPqxI6DTgm3tNmsm2eaRWLVWTF5meCjmde4e3FbRxV79nxEGDebUqRBYrwNDPgUQ/exec?sheet=Blad1&range=D6:D10](https://script.google.com/macros/s/AKfycby6hghPqxI6DTgm3tNmsm2eaRWLVWTF5meCjmde4e3FbRxV79nxEGDebUqRBYrwNDPgUQ/exec?sheet=Blad1&range=D6:D10)). When you view that url you should see something like this: 
![image](https://github.com/user-attachments/assets/b46daf0c-43da-41f7-8608-821f321ce375)

**Comment by ryan-d-williams** [comment]
@FallandeGubbe 

Yes as long as it is available on the pi it should work. This is not a problem with the module but rather a problem with something in your setup. 

If you're comfortable with code, you can try printing out the `requestError` in the `node_helper` file. You can add a new line 53 that reads:
```
console.log(requestError)
```

That might give us some more info on exactly why the request is failing on your pi.

**Comment by FallandeGubbe** [comment]
ok, thanks.
No I am far from a coder, but I added the code you suggested.

Same result - Would I be able so see a log file somewhere?

**Comment by ryan-d-williams** [comment]
@FallandeGubbe 

That code would print the error to the developer console in the browser. If you don't know how to access that you can change that line you added to:
```
Log.info(requestError
```

And it will then print to the terminal (where you start MM from)

**Comment by FallandeGubbe** [comment]
OK! 

Does this help? 

[20.10.2024 20:13.48.090] [LOG]   [MMM-GoogleSheets] Sending request to https://script.google.com/macros/s/AKfycby6hghPqxI6DTgm3tNmsm2eaRWLVWTF5meCjmde4e3FbRxV79nxEGDebUqRBYrwNDPgUQ/exec?sheet=Blad1&range=D6:D10
[20.10.2024 20:13.48.109] [INFO]  ReferenceError: fetch is not defined
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-GoogleSheets/node_helper.js:28:24)
    at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:109:11)
    at Socket.emit (events.js:315:20)
    at Socket.emitUntyped (/home/pi/MagicMirror/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/pi/MagicMirror/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[20.10.2024 20:13.48.125] [ERROR] [MMM-Google-Sheets] **ERROR** There was an error with the request at 20-Oct-24 20:13. This URL should work in your browser: https://script.google.com/macros/s/AKfycby6hghPqxI6DTgm3tNmsm2eaRWLVWTF5meCjmde4e3FbRxV79nxEGDebUqRBYrwNDPgUQ/exec?sheet=Blad1&range=D6:D10

**Comment by ryan-d-williams** [comment]
@FallandeGubbe 

The key here is "ReferenceError: fetch is not defined".

It looks like you are using an incorrect (old) version of nodejs. You can confirm this by tying this in your terminal:
```
node -v
```

My guess is it will show a version <18. The `fetch` function was only introduced in nodejs 18+. 

If you have an old node version, you need to upgrade.

If you have a current node version and it is still failing, you probably have an old version of MM [(this](https://forum.magicmirror.builders/topic/19056/referenceerror-fetch-is-not-defined) thread talks about this exact problem).

**Comment by ryan-d-williams** [comment]
I'm going to close this issue since this is not a module problem. If you still can't get it to work feel free to open it back up in the future.
