### ISSUE TITLE
Multiple Instances Issue

### ISSUE THREAD

**Issue by emrahaslan** [ryan-d-williams/MMM-GoogleSheets#6]
Hello again.

I have two diffrent sheet and I would like to show them with diffrenet pages.

I'ım using MMM-Pages module for this.

Page 1 - > Module for  Sheet 1  display
Page 2 - > Module for  Sheet 2  display

Could you please help me about this issue ?

**Comment by ryan-d-williams** [comment]
@emrahaslan I unfortunately cannot help with other modules. I would suggest posting to that module's repo if you are having issues with their module. There is no reason you cannot make multiple instance of this module however as long as both of the configurations are correct.

**Comment by emrahaslan** [comment]
Hi Ryan, I think there is missunderstood.

Could you please tell how can i duplicate this module?

I would like to display my “Sheet1” into bottom_left and my “Sheet2” into bottom_right. Is that possible?

**Comment by emrahaslan** [comment]
I need to two different instance like,

MMM-GoogleSheets
MMM-GoogleSheets_2

**Comment by ryan-d-williams** [comment]
@emrahaslan yes it is possible. You can just add them as two different instances in your config file, each with a separate location

`{
    module: "MMM-GoogleSheets",
    header: "First Instance",
    position: "bottom_left",
    config: {
        url:"url",
        sheet: "Sheet1",
        range: "range"
},{
    module: "MMM-GoogleSheets",
    header: "Second Instance",
    position: "top_left",
    config: {
        url:"url",
        sheet: "Sheet1",
        range: "range"
}`

You'll need to make sure the module name is not changed (if that's what you were trying with your most recent comment)
